set(_CATKIN_CURRENT_PACKAGE "vision_sim")
set(vision_sim_VERSION "0.0.0")
set(vision_sim_MAINTAINER "haleem <haleem@todo.todo>")
set(vision_sim_PACKAGE_FORMAT "2")
set(vision_sim_BUILD_DEPENDS )
set(vision_sim_BUILD_EXPORT_DEPENDS )
set(vision_sim_BUILDTOOL_DEPENDS "catkin")
set(vision_sim_BUILDTOOL_EXPORT_DEPENDS )
set(vision_sim_EXEC_DEPENDS )
set(vision_sim_RUN_DEPENDS )
set(vision_sim_TEST_DEPENDS )
set(vision_sim_DOC_DEPENDS )
set(vision_sim_URL_WEBSITE "")
set(vision_sim_URL_BUGTRACKER "")
set(vision_sim_URL_REPOSITORY "")
set(vision_sim_DEPRECATED "")